### ISSUE TITLE
1 GPU only ==> Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#25] opened 2018-01-05 00:10 UTC
With Beta 0.1 05JAN2018 (f36547e) :

![image](https://user-images.githubusercontent.com/7703320/34590086-da63a74e-f1b4-11e7-8fa4-b5444b2a29c3.png)

**Comment by UselessGuru** [comment] 2018-01-05 00:27
There is a problem with one of your miner files.

In the \Miners folder could you please rename ALL miner files to _*.* (Add an underscore at the beginning). 
Start MPM
Rename file back. Wait for 'Getting miner information'.
If OK rename next file ...

**Comment by hapklaar** [comment] 2018-01-05 00:30
This is a fresh copy with default miner files, guess that shouldn't be required?

**Comment by hapklaar** [comment] 2018-01-05 00:32
By the way, only happens on my desktop machine with only one GPU installed. On my 6x1070 I don't get this error.

**Comment by UselessGuru** [comment] 2018-01-05 00:38
I cannot reproduce the issue. I took the same files, no problem???

I have seen this issue reported a number of times. No answer so far. But is very valuable information that the problem is machine dependent. Do you have different GPU makes / models in both machines?
Could you please see if the above steps help.

**Comment by hapklaar** [comment] 2018-01-05 00:45
Have you tried reproducing on a one GPU machine? The error from #19 and this one make me think it has something to do with that.

Both machines have different types of GPU. The one GPU machine has an Asus STRIX GTX1080, the other one 6x Asus GTX1070.

The error happens for all miner files btw. Please see log attached.
[2018-01-05_01-44-14.txt](https://github.com/UselessGuru/MultiPoolMiner/files/1605209/2018-01-05_01-44-14.txt)

**Comment by UselessGuru** [comment] 2018-01-05 00:59
What about the stats folder? Also new?

**Comment by hapklaar** [comment] 2018-01-05 01:00
everything new

**Comment by UselessGuru** [comment] 2018-01-05 01:02
Hmm...

Line 193 is loading the miner files... 

I don't have another box to try. :-( can you send me one?

**Comment by hapklaar** [comment] 2018-01-05 01:11
Sure, you can have them all !
[Miners.zip](https://github.com/UselessGuru/MultiPoolMiner/files/1605239/Miners.zip)

**Comment by UselessGuru** [comment] 2018-01-05 01:56
I have added debug functionality to the [latest MultiPoolMiner.ps1](https://github.com/UselessGuru/MultiPoolMiner/commit/054a0ef43bfa5a8719d3829e369d0b9515e8ffbf).
This will dump variables to files so I can import and reproduce the issues (hopefully)

Howto:

1. Create a directory [MPM Dir]\Debug
2. Start MPM, let it run until the error appears, then let it do one more run. Stop
3. Pack the contents of the debug folder and upload
4. Remove debug folder

**Comment by UselessGuru** [comment] 2018-01-05 02:08
I have built in a debug feature in [MultiPoolMiner.ps1](https://github.com/UselessGuru/MultiPoolMiner/commit/c6823387a35b6ff910b227717d585a91db01a2fc). This can dump the contents of some the most important variable to files, which I can then import again to reproduce the problem.

Create a folder [MPMDir]\Debug and let  MPM run until you see the error.
Then pack the contents of the debug folder and upload here.

When done remove the debug folder

**Comment by hapklaar** [comment] 2018-01-05 02:11
Doesn't work unfortunately, nothing is being written to the Debug folder
[2018-01-05_03-05-09.txt](https://github.com/UselessGuru/MultiPoolMiner/files/1605322/2018-01-05_03-05-09.txt)
[MultiPoolMiner-2018-01-05.txt](https://github.com/UselessGuru/MultiPoolMiner/files/1605323/MultiPoolMiner-2018-01-05.txt)

**Comment by platinum4** [comment] 2018-01-05 04:41
He can't reproduce the problem because he does not have 1 GPU installed; this is a problem on single GPU rigs; it can be fixed by adding a `#` in front of line 193

**Comment by platinum4** [comment] 2018-01-05 04:56
OK if you comment out line 193 it will not save the power draws or the compute it just gets the hashrate for profitability on one card; so it's still broken

**Comment by platinum4** [comment] 2018-01-05 05:01
If you leave line 193 in, it will not load any of the miners

**Comment by hapklaar** [comment] 2018-01-05 11:05
hmm yes that;' why I asked

**Comment by hapklaar** [comment] 2018-01-05 11:06
(accidentally closed...)

Let me know if I can do more testing for this issue

**Comment by UselessGuru** [comment] 2018-01-05 14:21
Next version will come with better debug funtionality. So I think I can trace the cause then.

**Comment by UselessGuru** [comment] 2018-01-05 16:02
I have added debug functionality to the latest MultiPoolMiner.ps1.
This will dump variables to files so I can import and reproduce the issues (hopefully)

Howto:

Create a directory [MPM Dir]\Debug
Start MPM, let it run until the error appears, then let it do one more run. Stop
Pack the contents of the debug folder and upload
Remove debug folder

**Comment by hapklaar** [comment] 2018-01-05 22:28
This issue is still present on my 1 GPU rig. Please find the debug logs attached.
[Debug.zip](https://github.com/UselessGuru/MultiPoolMiner/files/1608101/Debug.zip)

**Comment by hapklaar** [comment] 2018-01-05 22:34
Not sure if it's relevant, but miners load fine when running setup.ps1

**Comment by platinum4** [comment] 2018-01-06 04:21
This is resolved by setting `$DeviceSubTypes = $True` in `Config.ps1`

**Comment by hapklaar** [comment] 2018-01-06 13:10
That's a negative. Doesn't work, same issue.

**Comment by hapklaar** [comment] 2018-01-06 13:19
[Debug.zip](https://github.com/UselessGuru/MultiPoolMiner/files/1608790/Debug.zip)
It is however continuing to download miners now. But error persists. Here's a new debug zip.

**Comment by rtom098** [comment] 2018-01-06 18:03
$DeviceSubTypes = $True in Config.ps1 > worked for me.

I also have just one card and got same error message before.

**Comment by UselessGuru** [comment] 2018-01-06 23:46
> $DeviceSubTypes = $True in Config.ps1 > worked for me.

Very interesting to know. This gives me an idea on where to locate the root cause.

**Comment by luismcv** [comment] 2018-01-10 21:29
I'm getting lots of this error per cycle after updating to https://github.com/UselessGuru/MultiPoolMiner/commit/ac6c02b8f74e4775d2752ab8ae9a97ffcc2c58d3 followed by a few 'DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".' which I don't know if they're somehow related.

I wasn't getting any of them when I was running https://github.com/UselessGuru/MultiPoolMiner/commit/12582783c255fc014a0cd6f4835d0fda882031b4. that might give you another hint about what change/s might cause them.

Doesn't seem to have any obvious effect on mining though it's annoying. 

I've got 3 GPUs, in two groups: 1x1080ti, 2x1070 ($DeviceSubTypes = $True), so I guess it also happens if a group only has 1 GPU.

---------
﻿Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\msn\Desktop\Mining\uselessGuru\MultiPoolMiner\MultiPoolMiner.ps1:207 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\msn\Desktop\Mining\uselessGuru\MultiPoolMiner\MultiPoolMiner.ps1:207 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

2018-01-10 21:18:14 INFO: Calculating profit for each miner...
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
DEBUG: "Sort-Object" - "Algorithm" cannot be found in "InputObject".
2018-01-10 21:23:29 INFO: Selected pool: ahashpool Zpool miningpoolhub

**Comment by UselessGuru** [comment] 2018-01-11 10:26
@hapklaar 

Unfortunately I cannot reproduce the issue with the data contained in the provided debug files :-(
I believe it might have to do with some MPM config settings.

Would you mind creating another debug file set using this version: https://github.com/UselessGuru/MultiPoolMiner/commit/0bfa1a3f23e0e968b70524d89cb5e984eac3b60b?

**Comment by UselessGuru** [comment] 2018-01-11 11:03
Does this help?
https://github.com/UselessGuru/MultiPoolMiner/commit/e86ca1e9a6685553a5231ffc6cd150342009e45a

**Comment by hapklaar** [comment] 2018-01-11 22:57
Yes, fixed.

**Comment by hapklaar** [comment] 2018-01-11 23:45
Sorry, issue still present when $DeviceSubTypes = $false
Debug attached.
[Debug.zip](https://github.com/UselessGuru/MultiPoolMiner/files/1624511/Debug.zip)

**Comment by jrafaelmdo** [comment] 2018-01-15 15:33
I can also confirm this bug is still present:

1 x 1080ti = crashed at launch with error "No miners available"
8 x 1060 = same MPM setup runs just fine
8 x 1070ti= same MPM setup just fine

FYI "vanilla" MPM works fine with single 1080ti. but I prefer your version better due to the added features.

**Comment by UselessGuru** [comment] 2018-05-02 22:56
Try https://github.com/UselessGuru/MultiPoolMiner/archive/master.zip

**Closed by UselessGuru** 2018-05-02 22:56 UTC
