### ISSUE TITLE
Miner restarts too soon

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#36] opened 2018-01-06 00:07 UTC
ccminer mining lyra2z takes a while to get up to speed. Looks like because of this, I get the following warnings causing constant miner restarts. Can this be tweaked?

![image](https://user-images.githubusercontent.com/7703320/34633680-076daae0-f27e-11e7-9374-18a874a401b5.png)

**Comment by UselessGuru** [comment] 2018-01-06 00:17
Yes, increase the interval, or https://github.com/UselessGuru/MultiPoolMiner/blob/master/README.txt

Q18. How to change fault tolerance limit to a higher percentage?
A18. Fault tolerance limit was implemented to detect unwanted negative or positive spikes in your hashrate caused by faulty miners or GPUs and prevent these statistics to be recorded to keep your benchmark data preserved in these unfortunate events. You should not feel the need to change this but first try to resolve the issues with your miners and/or devices. That said, if you are absolutely certain you want to change this, you can do so by amending the following line in Include.psm1:

`    [Math]::Min([Math]::Max($Stat.Week_Fluctuation * 2, 0.1), 0.9)`
    From:
    0.1
    To:
    0.3
This will change the fault tolerance limit from +/-10% to +30/-10%.

**Comment by hapklaar** [comment] 2018-01-06 00:26
Ok, got it. But this used to only be a warning preventing statistics from being updated that run, now it restarts the miner when this happens. Is this desired behaviour?

**Comment by UselessGuru** [comment] 2018-01-09 10:19
> ccminer mining lyra2z takes a while to get up to speed. Looks like because of this, I get the following warnings causing constant miner restarts. Can this be tweaked?

Frequenst miner restarts are fixed in newer build. They were caused by changing ports.

**Closed by UselessGuru** 2018-01-09 10:19 UTC
